name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Run linter
        run: |
          go install golang.org/x/lint/golint@latest
          golint -set_exit_status ./...

      - name: Run static analysis
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          staticcheck ./...

      - name: Run tests
        run: go test -v -race ./...

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          cache: true

      - name: Build for multiple platforms
        run: |
          GOOS=linux GOARCH=amd64 go build -o sabre-linux-amd64 .
          GOOS=darwin GOARCH=amd64 go build -o sabre-darwin-amd64 .
          GOOS=darwin GOARCH=arm64 go build -o sabre-darwin-arm64 .
          GOOS=windows GOARCH=amd64 go build -o sabre-windows-amd64.exe .

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: sabre-binaries
          path: |
            sabre-linux-amd64
            sabre-darwin-amd64
            sabre-darwin-arm64
            sabre-windows-amd64.exe
