name: Security

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  schedule:
    # Run security scans weekly
    - cron: "0 0 * * 0"

jobs:
  security:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.25.0"
          cache: true

      - name: Run Go security audit
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...

      - name: Run static analysis for security
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          staticcheck ./...

      - name: Check for secrets in code
        run: |
          docker run --rm -v "${{ github.workspace }}:/pwd" trufflesecurity/trufflehog:latest \
            filesystem --directory /pwd --only-verified --fail
